name: research_proj
channels:
  - default
  - conda-forge
  - nvidia
dependencies:
  - python=3.10
  - xorg-libsm
  - xorg-libxt
  - xorg-libxrender
  - unzip
  - ffmpeg
  - libffi
  - flex
  - bison
  - bzip2
  - libsqlite
  - llvm
  - ncurses=6.4
  - xz
  - tk
  - liblzma-devel
  - freeimage
  - pip
  - rust
  - setuptools<71
  - pip:
    - packaging==21.3
    - -r ./src/requirements.txt
