name: research_proj
channels:
  - default
  - conda-forge
  - nvidia
dependencies:
  - python=3.8
  # - cuda-toolkit=12.1
  - cuda-toolkit=11.8.0
  # - cudnn=8.9.7
  # - libcublas=12.4.5
  #alfred
  - xorg-libsm
  - libxt-conda-x86_64
  - xorg-libxrender
  - unzip
  - ffmpeg
  - libffi
  - flex
  - bison
  - bzip2
  - libsqlite
  - llvm
  - ncurses=6.4
  - xz
  - tk
  - liblzma-devel
  - freeimage
  # vild
  - hdf5
  - hdf5tools
  - zlib
  - libjpeg-turbo
  - libpng
  - zip
  - jpeg
  - pip
  - rust
  - pip:
    - setuptools
    - -r ./alfred/requirements.txt
    - -r ./percept-module/requirements.txt
